tap 'homebrew/cask'
tap 'heroku/brew'

brew 'asdf'
brew 'gh'
brew 'git'
brew 'heroku'
brew 'imagemagick'
brew 'libpq'
brew 'memcached'
brew 'postgresql'
brew 'redis'
brew 'shared-mime-info'
brew 'wget'

cask 'discord'
cask 'google-chrome'
cask 'slack'
cask 'spotify'
cask 'telegram-desktop'
cask 'visual-studio-code'
