tap 'heroku/brew'

brew 'cocoapods'
brew 'gh'
brew 'git'
brew 'heroku'
brew 'mise'
brew 'postgresql@14'
brew 'redis'

cask 'android-platform-tools'
cask 'android-studio'
cask 'discord'
cask 'google-chrome'
cask 'spotify'
cask 'telegram-desktop'
cask 'visual-studio-code'
